# Adapted from Github's Default Python Testing workflow
# Tests all backend code using PyTest as its framework
# Might set up docker deployment later

name: Backend Testing with PyTest

on:
  push:
    branches: [ "main", "fix-CICD" ]

permissions:
  contents: read

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4

    - name: Build docker container
      run: docker compose build --build-arg TEST=t
    
    - name: Run tests
      run: docker compose up
