# Adapted from Github's Default Python Testing workflow
# Tests all backend code using PyTest as its framework
# Might set up docker deployment later

name: Backend Testing with PyTest

on:
  push:
    branches: [ "main", "fix-CICD" ]

permissions:
  contents: read

jobs:
  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    # env:
    #   COMPOSE_FILE: ci/docker-compose.yml

    steps: 
    - uses: actions/checkout@v4

    - name: Build docker container
      run: docker compose build --build-arg TEST=t
      # working-directory: ${{ github.workspace }}/${{ env.COMPOSE_FILE }}

    - name: Run tests
      run: docker compose up

    - name: Exit
      if: success() || failure()
      run: docker compose down