name: frontend-testing

on:
  - push

jobs:
  test:
    name: Run Frontend Tests [todo]
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v4

    # - name: Build docker container
    #   run: docker compose build
    
    # - name: Run tests
    #   run: docker compose up --abort-on-container-exit

    - name: Exit
      if: success() || failure()
      run: docker compose down
